Repository xeon-protocol/xeon-dapp, pull requests merged in 2024-08, with the labels that each got.

#37 fix: switch to base sepolia on mobile web browsers
  .gitignore
  src/app/page.js
  src/components/ConnectWallet/NetworkChecker.js
Labels: type: bug

#38 fix: remove return buttons from token claim table
  src/components/testing/TokenTable.js
Labels: type: enhancement, type: bug

#26 docs: add bug bounty specs to SECURITY.md
  SECURITY.md
Labels: scope: documentation

#45 chore: cleanup unused imports
  .eslintrc.json
  src/app/claim/page.js
  src/app/dashboard/page.js
  src/app/guide/page.js
  src/app/page.js
  src/app/silkroad/page.js
  src/app/wallet/page.js
  src/components/Analytics/TokenInformation.js
  src/components/BookmarkAdded.js
  src/components/Card.js
  src/components/CenterNav.js
  src/components/ComingSoon.js
  src/components/ConnectWallet/NetworkChecker.js
  src/components/FailedPopup.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Layout.js
  src/components/LeftBarButton.js
  src/components/LiveTxs.js
  src/components/NoEvents.js
  src/components/NoMetaMask.js
  src/components/NoOtcTrades.js
  src/components/RightBarCard.js
  src/components/SocialPopup.js
  src/components/UnderConstruction.js
  src/components/dashboard/CenterNav.js
  src/components/dashboard/Layout.js
  src/components/dashboard/LeftBarButton.js
  src/components/dashboard/LeftBottomDates.js
  src/components/dashboard/LeftBottomWethValue.js
  src/components/dashboard/ProgressBar.js
  src/components/dashboard/RightBarCard.js
  src/components/guide/Deposit.js
  src/components/guide/HowItWorks.js
  src/components/guide/IntroCard.js
  src/components/guide/Testnet.js
  src/components/guide/UseCases.js
  src/components/guide/WhyOTC.js
  src/components/testing/TokenDeposits.js
  src/components/testing/TokenTable.js
  src/components/testing/Versions.js
  src/components/testing/WithdrawTokens.js
  src/components/testing/WriteHedges.js
  src/components/wallet/AssetsValues.js
  src/components/wallet/HedgesPanel.js
  src/components/wallet/RewardsPanel.js
  src/components/wallet/Staking.js
  src/components/wallet/Table.js
  src/components/wallet/UserAssets.js
  src/components/wallet/VaultBalances.js
Labels: type: enhancement, scope: UI

#48 fix: remove glitch text
  src/components/testing/TokenTable.js
Labels: type: enhancement, scope: UI

#43 feat: add PriceOracle.abi.json
  src/abi/PriceOracle.abi.json
Labels: type: enhancement, scope: contracts

#49 feat: add XeonHedging ABI and contract address
  src/abi/XeonHedging.abi.json
  src/abi/constants.js
Labels: type: enhancement, scope: contracts
