Repository xeon-protocol/xeon-dapp, pull requests merged in 2024-09, with the labels that each got.

#58 feat: add ABI for testnet XeonStakingPool
  src/abi/XeonStakingPool.abi.json
  src/abi/XeonTokenDistributor.abi.json
  src/abi/constants.js
Labels: scope: contracts

#61 feat: add testnet XEON to claim page
  src/abi/constants.js
  src/app/claim/page.js
  src/app/page.js
  src/components/testing/XeonTokenTable.js
Labels: scope: UI

#64 Fix/claim page update
  public/success.webp
  src/app/claim/page.js
  src/app/page.js
  src/components/Analytics/TokenInformation.js
  src/components/BookmarkAdded.js
  src/components/testing/TokenTable.js
  src/components/testing/XeonTokenTable.js
  src/components/wallet/HedgesPanel.js
  src/components/wallet/RewardsPanel.js
  src/components/wallet/Table.js
Labels: type: enhancement, scope: UI

#56 feat: update token select and use uniswap default token list
  package.json
  src/app/silkroad/page.js
  src/components/CenterNav.js
  src/components/Loans.js
  yarn.lock
Labels: DRAFT, scope: UI, status: waiting review

#66 feat: deploy staking page
  src/app/stake/page.js
  src/components/BookmarkAdded.js
  src/components/Header.js
  src/components/staking/UserAssets.js
  src/components/wallet/AssetsValues.js
Labels: type: enhancement, scope: UI
